__include__: [
  '../dataset/ccd_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/dfine_hgnetv2.yml',
]

output_dir: output/dfine_hgnetv2_m_ccd/6_1/38


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DFINETransformer:
  num_layers: 4  # 5 6
  eval_idx: -1  # -2 -3

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

optimizer:
  type: AdamW
  params:
    -
      # 捕获 VisualClassifier 下的所有参数，不论是普通权重还是 BN
      params: '^(?=.*VisualClassifier).*$'
      lr: 0.00002
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      # lr: 0.00002
      lr: 0.00004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      # lr: 0.00002
      lr: 0.00004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  # lr: 0.0002
  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.00012
#   weight_decay: 0.00005  # Faster convergence (optional)


# epochs: 100 # Early stop
epochs: 150
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 500
  collate_fn:
    stop_epoch: 500
    base_size_repeat: 6

checkpoint_freq: 2
print_freq: 100

pretrain_vpe: False

grpo_cls: True
grpo_finetune: False
grpo_advantage_weight: 0.01
grpo_beta: 0.04
grpo_num_mute: 300
epsilon: 0.000000001
iou_pro_reward: True
